In [2]:
a = 3

In [3]:
a

3

In [4]:
print(type(5))

<class 'int'>

In [ ]:
# Data Structures

1. List [] -> mutable, ordered, allows duplicates
2. Tuple () -> immutable, ordered, allows duplicates
3. Set {} -> mutable, unordered, does not allow duplicates
4. Dictionary {} -> mutable, unordered, key-value pairs

In [5]:
# list
list_buah = ['apel', 'jeruk', 'mangga', 'pisang', 'anggur']

In [ ]:
list_buah[0] # akses elemen pertama
list_buah[0:3] # akses elemen pertama, kedua, dan ketiga

['apel', 'mangga', 'anggur']

In [14]:
list_buah[::2] # stepping

['apel', 'mangga', 'anggur']

In [15]:
list_buah.append('kiwi') # menambahkan elemen di akhir list

In [17]:
list_buah.pop()

'kiwi'

In [18]:
list_buah

['apel', 'jeruk', 'mangga', 'pisang', 'anggur']

In [19]:
# tuple
tuple(list_buah) # konversi list ke tuple

('apel', 'jeruk', 'mangga', 'pisang', 'anggur')

In [20]:
# Dictionary -> {key: value}
dict_buah = { 'buah' : ('apel', 'jeruk', 'mangga', 'pisang', 'anggur') }
print(dict_buah)

{'buah': ('apel', 'jeruk', 'mangga', 'pisang', 'anggur')}

In [23]:
ktp = True

In [24]:
# one linear expression
# result_if_true if condition else result_if_false

'boleh mengendari mobil' if ktp == True else 'tidak boleh mengendarai mobil'

'boleh mengendari mobil'

In [27]:
# looping -> for each loop, while loop (digunakan ketika kita ingin mengulang selama suatu kondisi bernilai True)
i = 0
while i < 10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9

In [28]:
for i in range(10): # range(start, stop, step)
    print(i)

0
1
2
3
4
5
6
7
8
9

In [29]:
for i in list_buah:
    print(i)

apel
jeruk
mangga
pisang
anggur

In [30]:
for i in range(len(list_buah)):
    print(i)

0
1
2
3
4

In [31]:
# list comprehension -> membuat list baru dari list yang sudah ada
[i for i in range(10)]

[0, 1, 2, 3, 4]

In [32]:
[i for i in range(10) if i % 2 == 0]

[0, 2, 4, 6, 8]

In [36]:
# function
# def sapa():
#     print('Halo, selamat datang di kelas DSML!')

def sapa(i):
    print(f'Halo, selamat datang di kelas DSML, {i}!')

sapa('Andi')

Halo, selamat datang di kelas DSML, Andi!

In [39]:
# nameless function -> lambda function
(lambda x: x ** 2)(5)

25

In [40]:
import numpy as np

In [42]:
arr1 = np.array([1, 2, 3, 4, 5])

In [43]:
arr1.shape

(5,)

In [46]:
arr1.ndim

1

In [47]:
arr1 + 3

array([4, 5, 6, 7, 8])

In [52]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [5, 3, 2, 8, 6]])

In [54]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 5,  3,  2,  8,  6]])

In [ ]:
arr2[1, 1]

array([1, 6, 5])

In [57]:
arr2[:, 0]

array([[3, 4],
       [8, 9]])

In [60]:
arr2[:2,2:4]

array([[3, 4],
       [8, 9]])

In [61]:
arr2[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [ 5,  2,  6]])

In [62]:
arr2[::2,::2]

array([[1, 3, 5],
       [5, 2, 6]])

In [64]:
np.mean(arr2, axis=0) # mean per column

array([4.        , 4.        , 4.33333333, 7.        , 7.        ])

In [66]:
np.mean(arr2, axis=1) # mean per row

array([3. , 8. , 4.8])

In [67]:
arr2.reshape(5, 3) # reshape array menjadi 5 baris dan 3 kolom

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  5,  3],
       [ 2,  8,  6]])

In [68]:
array = np.random.randint(1, 100, size=(3, 5))

In [78]:
array

array([[23, 26,  2, 75, 43],
       [55, 79, 31, 12, 24],
       [50, 35, 54, 19, 53]], dtype=int32)

In [82]:
array[array > 50] # array dengan elemen yang lebih besar dari 50

array([75, 55, 79, 54, 53], dtype=int32)

In [85]:
array[(array > 50) & (array < 80)] # array dengan elemen yang lebih besar dari 50 dan lebih kecil dari 80
# and -> &, or -> |, not -> ~

array([75, 55, 79, 54, 53], dtype=int32)

In [1]:
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [7]:
df = sns.load_dataset('penguins')

In [10]:
df.columns()

TypeError: 'Index' object is not callable

In [11]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [12]:
df.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [13]:
df.sample(60)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
27,Adelie,Biscoe,40.5,17.9,187.0,3200.0,Female
185,Chinstrap,Dream,51.0,18.8,203.0,4100.0,Male
333,Gentoo,Biscoe,51.5,16.3,230.0,5500.0,Male
87,Adelie,Dream,36.9,18.6,189.0,3500.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
120,Adelie,Torgersen,36.2,17.2,187.0,3150.0,Female
301,Gentoo,Biscoe,52.5,15.6,221.0,5450.0,Male
142,Adelie,Dream,32.1,15.5,188.0,3050.0,Female
56,Adelie,Biscoe,39.0,17.5,186.0,3550.0,Female
178,Chinstrap,Dream,50.5,18.4,200.0,3400.0,Female
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,Female
78,Adelie,Torgersen,36.2,16.1,187.0,3550.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
131,Adelie,Torgersen,43.1,19.2,197.0,3500.0,Male
76,Adelie,Torgersen,40.9,16.8,191.0,3700.0,Female
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,Male
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
241,Gentoo,Biscoe,45.1,14.5,215.0,5000.0,Female
207,Chinstrap,Dream,52.2,18.8,197.0,3450.0,Male
224,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,Male
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,Female
89,Adelie,Dream,38.9,18.8,190.0,3600.0,Female
94,Adelie,Dream,36.2,17.3,187.0,3300.0,Female
55,Adelie,Biscoe,41.4,18.6,191.0,3700.0,Male
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,Male
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male
270,Gentoo,Biscoe,46.6,14.2,210.0,4850.0,Female
29,Adelie,Biscoe,40.5,18.9,180.0,3950.0,Male
65,Adelie,Biscoe,41.6,18.0,192.0,3950.0,Male
313,Gentoo,Biscoe,49.5,16.1,224.0,5650.0,Male
84,Adelie,Dream,37.3,17.8,191.0,3350.0,Female
159,Chinstrap,Dream,51.3,18.2,197.0,3750.0,Male
326,Gentoo,Biscoe,41.7,14.7,210.0,4700.0,Female
222,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,Female
51,Adelie,Biscoe,40.1,18.9,188.0,4300.0,Male
276,Gentoo,Biscoe,43.8,13.9,208.0,4300.0,Female
44,Adelie,Dream,37.0,16.9,185.0,3000.0,Female
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,Female
314,Gentoo,Biscoe,44.5,14.7,214.0,4850.0,Female
172,Chinstrap,Dream,42.4,17.3,181.0,3600.0,Female
88,Adelie,Dream,38.3,19.2,189.0,3950.0,Male
265,Gentoo,Biscoe,43.6,13.9,217.0,4900.0,Female
198,Chinstrap,Dream,50.1,17.9,190.0,3400.0,Female
167,Chinstrap,Dream,50.5,19.6,201.0,4050.0,Male
202,Chinstrap,Dream,48.1,16.4,199.0,3325.0,Female
303,Gentoo,Biscoe,50.0,15.9,224.0,5350.0,Male
295,Gentoo,Biscoe,48.6,16.0,230.0,5800.0,Male
284,Gentoo,Biscoe,45.8,14.2,219.0,4700.0,Female
121,Adelie,Torgersen,37.7,19.8,198.0,3500.0,Male
323,Gentoo,Biscoe,49.1,15.0,228.0,5500.0,Male
242,Gentoo,Biscoe,46.5,14.5,213.0,4400.0,Female
160,Chinstrap,Dream,46.0,18.9,195.0,4150.0,Female
206,Chinstrap,Dream,42.5,17.3,187.0,3350.0,Female
312,Gentoo,Biscoe,45.5,14.5,212.0,4750.0,Female
211,Chinstrap,Dream,45.6,19.4,194.0,3525.0,Female
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male
155,Chinstrap,Dream,45.4,18.7,188.0,3525.0,Female
59,Adelie,Biscoe,37.6,19.1,194.0,3750.0,Male
158,Chinstrap,Dream,46.1,18.2,178.0,3250.0,Female

In [14]:
df['species'] # Filter rows where species is 'Adelie'

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: str

In [15]:
df[['species', 'island']] # Filter rows where species is 'Adelie'

    species     island
0    Adelie  Torgersen
1    Adelie  Torgersen
2    Adelie  Torgersen
3    Adelie  Torgersen
4    Adelie  Torgersen
..      ...        ...
339  Gentoo     Biscoe
340  Gentoo     Biscoe
341  Gentoo     Biscoe
342  Gentoo     Biscoe
343  Gentoo     Biscoe

[344 rows x 2 columns]

In [16]:
df[df['species'] == 'Adelie'] # Filter rows where species is 'Adelie'

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,Female
148,Adelie,Dream,36.0,17.8,195.0,3450.0,Female
149,Adelie,Dream,37.8,18.1,193.0,3750.0,Male
150,Adelie,Dream,36.0,17.1,187.0,3700.0,Female
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male

In [20]:
df[(df['island'] == 'Torgersen') & (df['bill_length_mm'] > 40)].reset_index(drop=True) # Filter rows where island is 'Torgersen' and bill_length_mm is greater than 40

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
1,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN
2,Adelie,Torgersen,41.1,17.6,182.0,3200.0,Female
3,Adelie,Torgersen,42.5,20.7,197.0,4500.0,Male
4,Adelie,Torgersen,46.0,21.5,194.0,4200.0,Male
5,Adelie,Torgersen,41.8,19.4,198.0,4450.0,Male
6,Adelie,Torgersen,45.8,18.9,197.0,4150.0,Male
7,Adelie,Torgersen,42.8,18.5,195.0,4250.0,Male
8,Adelie,Torgersen,40.9,16.8,191.0,3700.0,Female
9,Adelie,Torgersen,42.1,19.1,195.0,4000.0,Male
10,Adelie,Torgersen,42.9,17.6,196.0,4700.0,Male
11,Adelie,Torgersen,41.1,18.6,189.0,3325.0,Male
12,Adelie,Torgersen,40.2,17.0,176.0,3450.0,Female
13,Adelie,Torgersen,41.4,18.5,202.0,3875.0,Male
14,Adelie,Torgersen,40.6,19.0,199.0,4000.0,Male
15,Adelie,Torgersen,41.5,18.3,195.0,4300.0,Male
16,Adelie,Torgersen,44.1,18.0,210.0,4000.0,Male
17,Adelie,Torgersen,43.1,19.2,197.0,3500.0,Male

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [ ]:
# loc -> label location/index
# iloc -> index location/index

In [22]:
df.loc[6:10]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN

In [28]:
df.iloc[6:10, 0:2] # Filter rows from index 6 to 9 and columns from index 0 to 2

  species     island
6  Adelie  Torgersen
7  Adelie  Torgersen
8  Adelie  Torgersen
9  Adelie  Torgersen

In [29]:
df.loc[6:10, ['species', 'island']] # Filter rows from index 6 to 9 and columns 'species' and 'island'

   species     island
6   Adelie  Torgersen
7   Adelie  Torgersen
8   Adelie  Torgersen
9   Adelie  Torgersen
10  Adelie  Torgersen

## Data Manipulation
add column/row
drop column/row